Repository open-atmos/PySDM, pull requests merged in 2024-12, with the labels that each got.

#1444 switch to dark mode for docs
  docs/templates/README.md
  docs/templates/custom.css
  docs/templates/syntax-highlighting.css
  docs/templates/theme.css
Labels: documentation

#1439 Vtk exporter fix to save more than one product
  PySDM/exporters/vtk_exporter.py
  tests/unit_tests/exporters/__init__.py
  tests/unit_tests/exporters/test_vtk_exporter.py
Labels: bug, VTK

#1461 CI workflows: do not run tests/examples on release (run only before and after merging); move pdoc and pypi workflows to separate .yml files
  .github/workflows/pdoc.yml
  .github/workflows/pypi.yml
  .github/workflows/tests.yml
  tests/examples_tests/test_tests_completeness.py
Labels: CI

#1451 shorten CI times by: moving some smoke tests to a new parcel_d; dividing examples into more suites
  .github/workflows/tests.yml
  examples/PySDM_examples/Arabas_et_al_2015/gui.ipynb
  examples/PySDM_examples/Arabas_et_al_2015/paraview_hello_world.ipynb
  examples/PySDM_examples/Bartman_2020_MasterThesis/fig_4_adaptive_sdm.py
  examples/PySDM_examples/Bartman_2020_MasterThesis/fig_5_SCIPY_VS_ADAPTIVE.py
  examples/PySDM_examples/Berry_1967/figs_5_8_10.ipynb
  examples/PySDM_examples/Shima_et_al_2009/fig_2.ipynb
  tests/examples_tests/conftest.py
  tests/smoke_tests/parcel_b/__init__.py
  tests/smoke_tests/parcel_d/__init__.py
  tests/smoke_tests/parcel_d/jensen_and_nugent_2017/__init__.py
  tests/smoke_tests/parcel_d/jensen_and_nugent_2017/test_fig_1.py
  tests/smoke_tests/parcel_d/jensen_and_nugent_2017/test_fig_3_and_tab_4_upper_rows.py
  tests/smoke_tests/parcel_d/jensen_and_nugent_2017/test_fig_4_and_7_and_tab_4_bottom_rows.py
  tests/smoke_tests/parcel_d/jensen_and_nugent_2017/test_fig_5.py
  tests/smoke_tests/parcel_d/jensen_and_nugent_2017/test_fig_6.py
  tests/smoke_tests/parcel_d/jensen_and_nugent_2017/test_table_3.py
  tests/smoke_tests/parcel_d/kreidenweis_et_al_2003/__init__.py
  tests/smoke_tests/parcel_d/kreidenweis_et_al_2003/test_fig_1.py
  tests/smoke_tests/parcel_d/kreidenweis_et_al_2003/test_ionic_strength.py
  tests/smoke_tests/parcel_d/kreidenweis_et_al_2003/test_spectrum_at_t_0.py
  tests/smoke_tests/parcel_d/kreidenweis_et_al_2003/test_table_3.py
  tests/smoke_tests/parcel_d/niedermeier_et_al_2013/__init__.py
  tests/smoke_tests/parcel_d/niedermeier_et_al_2013/test_temperature_profile.py
  tests/smoke_tests/parcel_d/rozanski_and_sonntag_1982/__init__.py
  tests/smoke_tests/parcel_d/rozanski_and_sonntag_1982/test_figs_4_5_6.py
  tests/smoke_tests/parcel_d/seeding/__init__.py
  tests/smoke_tests/parcel_d/seeding/test_hello_world.py
  tests/smoke_tests/parcel_d/seeding/test_seeding_no_collisions.py
  tests/smoke_tests/parcel_d/yang_et_al_2018/__init__.py
  tests/smoke_tests/parcel_d/yang_et_al_2018/test_displacement.py
  tests/smoke_tests/parcel_d/yang_et_al_2018/test_initialisation.py
  tests/smoke_tests/parcel_d/yang_et_al_2018/test_just_do_it.py
Labels: CI
